### ISSUE TITLE
Nvidia GPU

### ISSUE THREAD

**Issue by Hexagram6716** [natankeddem/hush#4]
I have given the container my nvidia gpu and it still cant see it i get Invalid selection.

**Comment by natankeddem** [comment]
What do you mean by the phrase "I have given the container my nvidia gpu"? Hush is not able to utilize any "local" sensor data, internal to the container, all sensors use a "remote" connection. In the case of an nVidia GPU, nvidia-smi is utilized via an SSH session. If you SSH into the target machine OS which houses the GPU and execute `nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader` what does that give you?

**Comment by Hexagram6716** [comment]
Hi Natankeddem

nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader
65

the setup I have is proxmox host. I assumed that it would get the nvidia gpu temp via the container having access to it 

my setup is 
Proxmox
Portainer/Docker -? hush. Works fine so far for cpu and fan control

I dropped you a message in homelab discord if thats easier
