### ISSUE TITLE
Feature Request - Logging to MQTT server 

### ISSUE THREAD

**Issue by ComputerComa** [natankeddem/hush#6]
Good morning! First off I absoutely love this software.. I've been running it for a couple months now and it's been running flawless. However I have one request for what may be a niche use case (or maybe not idk) 
I Would love for an option to publish Current temperatures and reported / set fan speeds to a MQTT server (and possibly adding MQTT auto discovery for home assistant )..
Idk if this is possible at all but if you could implement this but if you could I would be greatly thankful. 
Thanks for all your hard work and I look forward to hearing your feedback.

**Comment by natankeddem** [comment]
Hi @ComputerComa,
Thank you for your kind words. I am unfamiliar with the MQTT protocol, but I can try to learn and add support for it. You stated ingestion of this data into Home Assistant possibly? Is there a specific MQTT server/ingestion app you are working with here? Or are you just dealing with a standard feature build into stock Home Assistant? This would give me something to go off of for my research.

**Comment by ComputerComa** [comment]
MQTT should be platform agnostic as it's a standardized protocol. I personally am running the Mosquitto MQTT broker.  As for the MQTT autodiscovery for home assistant, Here's a link to their documentation on their website [Home Assistant MQTT Sensor](https://www.home-assistant.io/integrations/sensor.mqtt/) it's a built in feature when using the MQTT integration.

**Comment by natankeddem** [comment]
Thank you @ComputerComa for your help with doing initial testing for this feature. I have implemented it into https://github.com/natankeddem/hush/releases/tag/v3.0.19.
